// replcae later

#pragma once

#include "NativeGameplayTags.h"

namespace AGGameplayTags
{
	/** Input Tags **/
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);

	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
	
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);

	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block);

	/** Player Tags **/
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block);

	
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
	
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
	
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SuccessfulBlock);

	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Status_JumpToFinisher);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Status_Rolling);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking);

	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);

	/** Enemy Tags **/
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);

	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack);
	
	/** Shared Tags **/
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);
	
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);

	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Death);
	
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left);
	ACTIONGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right);

}